server:
  port: 8094
  
spring:
  application:
    name: micro-account
  data:
    mongodb:
      uri: mongodb://localhost:12500/account
      
kafka:
  server:
    hostname: localhost
    port: 29092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/