server:
  port: 8090
  
spring:
  application:
    name: micro-customer
  data:
    mongodb:
#      uri: mongodb://localhost:12500/customer
      uri: mongodb://bootcamb-db:uMamqpjJ0iG4gPsLyJXEAaqfW8685r2SEWaIYmBvtH9aYigkhka31qHcEazga17iyFoWmkEHbZNQRpQAUdTnbg==@bootcamb-db.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@bootcamb-db@      
  kafka:
    bootstrap-servers: localhost:29092

kafka:
  server:
    hostname: localhost
    port: 29092
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8099/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost

