server:
  port: 8098
  
spring:
  application:
    name: micro-credit-payment
  data:
    mongodb:
      uri: mongodb://localhost:12500/payment
      
kafka:
  server:
    hostname: localhost
    port: 29092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/