server:
  port: 8094
  
spring:
  application:
    name: micro-account
  data:
    mongodb:
      uri: mongodb://localhost:27017/account
      
kafka:
  server:
    hostname: localhost
    port: 9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/