server:
  port: 8091
  
spring:
  application:
    name: micro-product
  data:
    mongodb:
      uri: mongodb://localhost:12500/product
      
kafka:
  server:
    hostname: localhost
    port: 9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/