server:
  port: 8090
  
spring:
  application:
    name: micro-customer
  data:
    mongodb:
      uri: mongodb://localhost:12500/customer

kafka:
  server:
    hostname: localhost
    port: 29092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

