server:
  port: 8093
  
spring:
  application:
    name: micro-transaction
  data:
    mongodb:
      uri: mongodb://localhost:27017/transaction

kafka:
  server:
    hostname: localhost
    port: 9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
