server:
  port: 8090
  
spring:
  application:
    name: customer
  data:
    mongodb:
      uri: mongodb://localhost:27017/customer

kafka:
  server:
    hostname: localhost
    port: 9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

topic:
  groupid: customer-consumer
  purchase:
    names: purchase-topic