server:
  port: 8090
  
spring:
  application:
    name: micro-customer
  data:
    mongodb:
#      uri: mongodb://localhost:12500/customer
      uri: mongodb://bootcamb-db:uMamqpjJ0iG4gPsLyJXEAaqfW8685r2SEWaIYmBvtH9aYigkhka31qHcEazga17iyFoWmkEHbZNQRpQAUdTnbg==@bootcamb-db.mongo.cosmos.azure.com:10255/customer?ssl=true&retrywrites=false&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@bootcamb-db@      
  kafka:
#    bootstrap-servers: 13.87.186.84:29092
#    bootstrap-servers: 13.64.20.193:9092
     bootstrap-servers: 192.168.1.136:9092
kafka:
  server:
    hostname: 192.168.1.136
    port: 9092
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:80/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: servidor-eureka.azurewebsites.net

