server:
  port: 8093
  
spring:
  application:
    name: micro-transaction
  data:
    mongodb:
      uri: mongodb://localhost:12500/transaction
  kafka:
    bootstrap-servers: localhost:29092

kafka:
  server:
    hostname: localhost
    port: 29092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
