server:
  port: 8092
  
spring:
  application:
    name: micro-purchase
  data:
    mongodb:
      uri: mongodb://localhost:12500/purchase
  kafka:
    bootstrap-servers: localhost:29092

kafka:
  server:
    hostname: localhost
    port: 29092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
