server:
  port: 8092
  
spring:
  application:
    name: micro-purchase
  data:
    mongodb:
      uri: mongodb://localhost:12500/purchase

kafka:
  server:
    hostname: localhost
    port: 9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
