server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: customer-service
        uri: lb://micro-customer
        predicates:
        - Path=/customer/**
      - id: product-service
        uri: http://localhost:8091/
        predicates:
        - Path=/product/**
#      - id: purchase-service
#        uri: http://localhost:8092/
#        predicates:
#        - Path=/purchase/**
#      - id: transaction-service
#        uri: http://localhost:8093/
#        predicates:
#        - Path=/transaction/**
#      - id: account-service
#        uri: http://localhost:8094/
#        predicates:
#        - Path=/account/**
#      - id: withdrawal-service
#        uri: http://localhost:8095/
#        predicates:
#        - Path=/withdrawal/**